language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit && sh make_dist.sh &&
  sh -c '
    RED="\033[0;31m"
    GREEN="\033[0;32m"
    NC="\033[0m"

    DIST_FILE="dist/Recommendation.phar";
    if [ -f $DIST_FILE ]; then
      echo "${GREEN}Successfully disting $DIST_FILE${NC}"
      exit 0
    else
      echo "${RED}Failed to dist $DIST_FILE${NC}"
      exit 1
    fi
  '